Repository today-clothes/my-closet, pull requests merged in 2022-02, with the labels that each got.

#126 :sparkles: 추천 기능 추가 (#65)
  backend/src/main/java/com/oclothes/domain/clothes/api/ClothesApiController.java
  backend/src/main/java/com/oclothes/domain/clothes/dao/ClothesRepository.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesMapperSupport.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesRecommendService.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesRecommendServiceImpl.java
  backend/src/main/java/com/oclothes/domain/user/domain/User.java
  backend/src/test/java/com/oclothes/domain/clothes/api/ClothesApiControllerTest.java
  backend/src/test/java/com/oclothes/domain/clothes/service/ClothesServiceImplTest.java
Labels: 🕋 백엔드, 🕹 기능

#129 :recycle: ClothesService 리팩토링 (#128)
  android/app/src/main/java/com/oclothes/mycloset/data/entities/Style.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/StyleInfo.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/InfoResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/SearchResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/StyleService.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/adapter/SingleClosetStyleListRVAdapter.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/search/SearchDetailFragment.kt
  backend/src/main/java/com/oclothes/domain/clothes/api/ClothesApiController.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesDto.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesMapper.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesMapperSupport.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesRecommendServiceImpl.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesService.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesServiceImpl.java
  backend/src/test/java/com/oclothes/domain/clothes/api/ClothesApiControllerTest.java
  backend/src/test/java/com/oclothes/domain/clothes/service/ClothesRecommendServiceImplTest.java
  backend/src/test/java/com/oclothes/domain/clothes/service/ClothesServiceImplTest.java
Labels: 🕋 백엔드, 🛠 리팩토링

#131 :recycle: ClothesServiceImpl save 메서드 리펙토링 (#130)
  backend/src/main/java/com/oclothes/domain/clothes/domain/Clothes.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesMapper.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/MapToTagDto.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesServiceImpl.java
Labels: 🕋 백엔드, 🛠 리팩토링

#134 :recycle: ClothesSupportRepositoryImpl 리펙토링 (#133)
  backend/src/main/java/com/oclothes/domain/clothes/dao/ClothesSupportRepositoryImpl.java
Labels: 🕋 백엔드, 🛠 리팩토링

#135 :bug: 옷 아이디 검색 버그 수정 (#132)
  backend/src/main/java/com/oclothes/domain/clothes/domain/Clothes.java
  backend/src/main/java/com/oclothes/domain/clothes/exception/ClothesAccessDeniedException.java
  backend/src/main/java/com/oclothes/domain/clothes/exception/ClothesExceptionMessage.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesServiceImpl.java
  backend/src/main/java/com/oclothes/global/error/RestControllerExceptionHandler.java
  backend/src/main/java/com/oclothes/global/error/exception/AuthorityException.java
Labels: 🐛 버그, 🕋 백엔드

#140 :sparkles: 옷장 목록 썸네일 이미지 url 제공 기능 추가 (#116)
  backend/src/main/java/com/oclothes/domain/closet/dto/ClosetDto.java
  backend/src/main/java/com/oclothes/domain/closet/dto/ClosetMapper.java
  backend/src/main/java/com/oclothes/domain/closet/service/ClosetServiceImpl.java
  backend/src/main/java/com/oclothes/domain/clothes/api/ClothesApiController.java
  backend/src/main/java/com/oclothes/domain/clothes/dao/ClothesRepository.java
  backend/src/main/java/com/oclothes/domain/clothes/dto/ClothesResponseMessage.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesService.java
  backend/src/main/java/com/oclothes/domain/clothes/service/ClothesServiceImpl.java
  backend/src/test/java/com/oclothes/domain/closet/api/ClosetApiControllerTest.java
  backend/src/test/java/com/oclothes/domain/closet/service/ClosetServiceImplTest.java
  backend/src/test/java/com/oclothes/domain/clothes/domain/ClothesRepositoryTest.java
Labels: 🕋 백엔드, 🕹 기능

#148 :sparkles: 마이페이지 구현 (#64)
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/service/ClosetService.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/view/ClosetCreateView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/view/ClosetDeleteView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/view/ClosetUpdateView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/view/ClosetView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/controller/UserRetrofitInterface.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/AccountDto.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/InfoResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/LoginResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/PersonalDto.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/SignUpDto.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/SignUpResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/UpdateResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/dto/UserDto.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/service/UserService.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/view/AccountUpdateView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/view/PersonalUpdateView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/view/UserInfoView.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/login/login/LoginLoginActivity.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/login/login/LoginView.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/MainActivity.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/ClosetFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/mypage/MyPageFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/mypage/modify/ModifyInfoActivity.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/signup/SignUpActivity.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/signup/SignUpEmailFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/splash/SplashActivity.kt
  android/app/src/main/java/com/oclothes/mycloset/utils/RegulationUtils.kt
  android/app/src/main/java/com/oclothes/mycloset/utils/SharedPreferenceManager.kt
  android/app/src/main/res/layout/activity_modify_info.xml
  android/app/src/main/res/layout/fragment_my_page.xml
  android/app/src/main/res/layout/fragment_sign_up_email.xml
  android/app/src/main/res/layout/item_searched_item.xml
Labels: 📱 안드로이드, 🕹 기능

#149 :sparkles: 옷장페이지 썸네일 추가 (#144)
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/dto/ClosetResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/service/ClosetService.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/domain/Closet.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/user/service/UserService.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/ClosetFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/DetailFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/StyleFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/adapter/ClosetListRVAdapter.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/adapter/SingleClosetStyleListRVAdapter.kt
Labels: 📱 안드로이드, 🕹 기능

#151 페이징 기능 구현 (#150)
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/controller/ClosetRetrofitInterface.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/dto/ClosetResponse.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/service/ClosetService.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/closet/view/ClosetView.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/controller/StyleRetrofitInterface.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/service/StyleService.kt
  android/app/src/main/java/com/oclothes/mycloset/data/entities/remote/style/view/StyleSearchView.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/ClosetFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/closet/StyleFragment.kt
  android/app/src/main/java/com/oclothes/mycloset/ui/main/search/SearchFragment.kt
  android/app/src/main/res/layout/fragment_closet.xml
  android/app/src/main/res/layout/fragment_search.xml
  android/app/src/main/res/layout/fragment_single_closet.xml
Labels: 📱 안드로이드, 🕹 기능
